export const ACTION_TYPES = {
    CREATE_A_POST: "CREATE_A_POST", 
    SEARCH_ACTION: "SEARCH_ACTION", 
    INITIALIZE: "INITIALIZE", 
    LIKE_A_POST: "LIKE_A_POST",
    DISLIKE_A_POST: "DISLIKE_A_POST"

}